version: '3.3'
services:
  postgres:
    image: mdillon/postgis:10
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iot_heartbeat_dev
      PGDATA: /data
    volumes:
      - ./priv/postgres:/data
